//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSWinCom.PollingApiExampleConsoleApp.PollingApi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcknowledgeResponse", Namespace="http://pswin.com/SOAP/Poll")]
    [System.SerializableAttribute()]
    public partial class AcknowledgeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FetchResponse", Namespace="http://pswin.com/SOAP/Poll")]
    [System.SerializableAttribute()]
    public partial class FetchResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PSWinCom.PollingApiExampleConsoleApp.PollingApi.IncomingSMSMessage SMSMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MessageTimestamp {
            get {
                return this.MessageTimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTimestampField, value) != true)) {
                    this.MessageTimestampField = value;
                    this.RaisePropertyChanged("MessageTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.IncomingSMSMessage SMSMessage {
            get {
                return this.SMSMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSMessageField, value) != true)) {
                    this.SMSMessageField = value;
                    this.RaisePropertyChanged("SMSMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncomingSMSMessage", Namespace="http://pswin.com/SOAP/Poll")]
    [System.SerializableAttribute()]
    public partial class IncomingSMSMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        private string NetworkField;
        
        private string AddressField;
        
        private PSWinCom.PollingApiExampleConsoleApp.PollingApi.GSMPosition PositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReceiverNumber {
            get {
                return this.ReceiverNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverNumberField, value) != true)) {
                    this.ReceiverNumberField = value;
                    this.RaisePropertyChanged("ReceiverNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderNumber {
            get {
                return this.SenderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderNumberField, value) != true)) {
                    this.SenderNumberField = value;
                    this.RaisePropertyChanged("SenderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Network {
            get {
                return this.NetworkField;
            }
            set {
                if ((object.ReferenceEquals(this.NetworkField, value) != true)) {
                    this.NetworkField = value;
                    this.RaisePropertyChanged("Network");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.GSMPosition Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GSMPosition", Namespace="http://pswin.com/SOAP/Poll")]
    [System.SerializableAttribute()]
    public partial class GSMPosition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LattitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RadiusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CouncilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CouncilNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Lattitude {
            get {
                return this.LattitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LattitudeField, value) != true)) {
                    this.LattitudeField = value;
                    this.RaisePropertyChanged("Lattitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Radius {
            get {
                return this.RadiusField;
            }
            set {
                if ((object.ReferenceEquals(this.RadiusField, value) != true)) {
                    this.RadiusField = value;
                    this.RaisePropertyChanged("Radius");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Council {
            get {
                return this.CouncilField;
            }
            set {
                if ((object.ReferenceEquals(this.CouncilField, value) != true)) {
                    this.CouncilField = value;
                    this.RaisePropertyChanged("Council");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CouncilNumber {
            get {
                return this.CouncilNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CouncilNumberField, value) != true)) {
                    this.CouncilNumberField = value;
                    this.RaisePropertyChanged("CouncilNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SubPlace {
            get {
                return this.SubPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.SubPlaceField, value) != true)) {
                    this.SubPlaceField = value;
                    this.RaisePropertyChanged("SubPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FetchDRResponse", Namespace="http://pswin.com/SOAP/Poll")]
    [System.SerializableAttribute()]
    public partial class FetchDRResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryReportIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DelivertReportTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PSWinCom.PollingApiExampleConsoleApp.PollingApi.DeliveryReport DeliveryReportMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DeliveryReportID {
            get {
                return this.DeliveryReportIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryReportIDField, value) != true)) {
                    this.DeliveryReportIDField = value;
                    this.RaisePropertyChanged("DeliveryReportID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DelivertReportTimestamp {
            get {
                return this.DelivertReportTimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.DelivertReportTimestampField, value) != true)) {
                    this.DelivertReportTimestampField = value;
                    this.RaisePropertyChanged("DelivertReportTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.DeliveryReport DeliveryReportMessage {
            get {
                return this.DeliveryReportMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryReportMessageField, value) != true)) {
                    this.DeliveryReportMessageField = value;
                    this.RaisePropertyChanged("DeliveryReportMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryReport", Namespace="http://pswin.com/SOAP/Poll")]
    [System.SerializableAttribute()]
    public partial class DeliveryReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverNumberField;
        
        private string DeliveryTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ReceiverNumber {
            get {
                return this.ReceiverNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverNumberField, value) != true)) {
                    this.ReceiverNumberField = value;
                    this.RaisePropertyChanged("ReceiverNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string DeliveryTime {
            get {
                return this.DeliveryTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryTimeField, value) != true)) {
                    this.DeliveryTimeField = value;
                    this.RaisePropertyChanged("DeliveryTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pswin.com/SOAP/Poll", ConfigurationName="PollingApi.PollSoap")]
    public interface PollSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://pswin.com/SOAP/Poll is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pswin.com/SOAP/Poll/AcknowledgeMessage", ReplyAction="*")]
        PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeMessageResponse AcknowledgeMessage(PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeMessageRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://pswin.com/SOAP/Poll is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pswin.com/SOAP/Poll/FetchNextMessage", ReplyAction="*")]
        PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextMessageResponse FetchNextMessage(PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextMessageRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://pswin.com/SOAP/Poll is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pswin.com/SOAP/Poll/FetchNextDeliveryReport", ReplyAction="*")]
        PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextDeliveryReportResponse FetchNextDeliveryReport(PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextDeliveryReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcknowledgeMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcknowledgeMessage", Namespace="http://pswin.com/SOAP/Poll", Order=0)]
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeMessageRequestBody Body;
        
        public AcknowledgeMessageRequest() {
        }
        
        public AcknowledgeMessageRequest(PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pswin.com/SOAP/Poll")]
    public partial class AcknowledgeMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageId;
        
        public AcknowledgeMessageRequestBody() {
        }
        
        public AcknowledgeMessageRequestBody(string username, string password, string messageId) {
            this.username = username;
            this.password = password;
            this.messageId = messageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcknowledgeMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcknowledgeMessageResponse", Namespace="http://pswin.com/SOAP/Poll", Order=0)]
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeMessageResponseBody Body;
        
        public AcknowledgeMessageResponse() {
        }
        
        public AcknowledgeMessageResponse(PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pswin.com/SOAP/Poll")]
    public partial class AcknowledgeMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeResponse AcknowledgeMessageResult;
        
        public AcknowledgeMessageResponseBody() {
        }
        
        public AcknowledgeMessageResponseBody(PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeResponse AcknowledgeMessageResult) {
            this.AcknowledgeMessageResult = AcknowledgeMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchNextMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchNextMessage", Namespace="http://pswin.com/SOAP/Poll", Order=0)]
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextMessageRequestBody Body;
        
        public FetchNextMessageRequest() {
        }
        
        public FetchNextMessageRequest(PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pswin.com/SOAP/Poll")]
    public partial class FetchNextMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool ackRequired;
        
        public FetchNextMessageRequestBody() {
        }
        
        public FetchNextMessageRequestBody(string username, string password, bool ackRequired) {
            this.username = username;
            this.password = password;
            this.ackRequired = ackRequired;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchNextMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchNextMessageResponse", Namespace="http://pswin.com/SOAP/Poll", Order=0)]
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextMessageResponseBody Body;
        
        public FetchNextMessageResponse() {
        }
        
        public FetchNextMessageResponse(PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pswin.com/SOAP/Poll")]
    public partial class FetchNextMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchResponse FetchNextMessageResult;
        
        public FetchNextMessageResponseBody() {
        }
        
        public FetchNextMessageResponseBody(PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchResponse FetchNextMessageResult) {
            this.FetchNextMessageResult = FetchNextMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchNextDeliveryReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchNextDeliveryReport", Namespace="http://pswin.com/SOAP/Poll", Order=0)]
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextDeliveryReportRequestBody Body;
        
        public FetchNextDeliveryReportRequest() {
        }
        
        public FetchNextDeliveryReportRequest(PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextDeliveryReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pswin.com/SOAP/Poll")]
    public partial class FetchNextDeliveryReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool ackRequired;
        
        public FetchNextDeliveryReportRequestBody() {
        }
        
        public FetchNextDeliveryReportRequestBody(string username, string password, bool ackRequired) {
            this.username = username;
            this.password = password;
            this.ackRequired = ackRequired;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchNextDeliveryReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchNextDeliveryReportResponse", Namespace="http://pswin.com/SOAP/Poll", Order=0)]
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextDeliveryReportResponseBody Body;
        
        public FetchNextDeliveryReportResponse() {
        }
        
        public FetchNextDeliveryReportResponse(PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextDeliveryReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pswin.com/SOAP/Poll")]
    public partial class FetchNextDeliveryReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchDRResponse FetchNextDeliveryReportResult;
        
        public FetchNextDeliveryReportResponseBody() {
        }
        
        public FetchNextDeliveryReportResponseBody(PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchDRResponse FetchNextDeliveryReportResult) {
            this.FetchNextDeliveryReportResult = FetchNextDeliveryReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PollSoapChannel : PSWinCom.PollingApiExampleConsoleApp.PollingApi.PollSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PollSoapClient : System.ServiceModel.ClientBase<PSWinCom.PollingApiExampleConsoleApp.PollingApi.PollSoap>, PSWinCom.PollingApiExampleConsoleApp.PollingApi.PollSoap {
        
        public PollSoapClient() {
        }
        
        public PollSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PollSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PollSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PollSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeMessageResponse PSWinCom.PollingApiExampleConsoleApp.PollingApi.PollSoap.AcknowledgeMessage(PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeMessageRequest request) {
            return base.Channel.AcknowledgeMessage(request);
        }
        
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeResponse AcknowledgeMessage(string username, string password, string messageId) {
            PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeMessageRequest inValue = new PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeMessageRequest();
            inValue.Body = new PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeMessageRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.messageId = messageId;
            PSWinCom.PollingApiExampleConsoleApp.PollingApi.AcknowledgeMessageResponse retVal = ((PSWinCom.PollingApiExampleConsoleApp.PollingApi.PollSoap)(this)).AcknowledgeMessage(inValue);
            return retVal.Body.AcknowledgeMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextMessageResponse PSWinCom.PollingApiExampleConsoleApp.PollingApi.PollSoap.FetchNextMessage(PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextMessageRequest request) {
            return base.Channel.FetchNextMessage(request);
        }
        
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchResponse FetchNextMessage(string username, string password, bool ackRequired) {
            PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextMessageRequest inValue = new PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextMessageRequest();
            inValue.Body = new PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextMessageRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.ackRequired = ackRequired;
            PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextMessageResponse retVal = ((PSWinCom.PollingApiExampleConsoleApp.PollingApi.PollSoap)(this)).FetchNextMessage(inValue);
            return retVal.Body.FetchNextMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextDeliveryReportResponse PSWinCom.PollingApiExampleConsoleApp.PollingApi.PollSoap.FetchNextDeliveryReport(PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextDeliveryReportRequest request) {
            return base.Channel.FetchNextDeliveryReport(request);
        }
        
        public PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchDRResponse FetchNextDeliveryReport(string username, string password, bool ackRequired) {
            PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextDeliveryReportRequest inValue = new PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextDeliveryReportRequest();
            inValue.Body = new PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextDeliveryReportRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.ackRequired = ackRequired;
            PSWinCom.PollingApiExampleConsoleApp.PollingApi.FetchNextDeliveryReportResponse retVal = ((PSWinCom.PollingApiExampleConsoleApp.PollingApi.PollSoap)(this)).FetchNextDeliveryReport(inValue);
            return retVal.Body.FetchNextDeliveryReportResult;
        }
    }
}
